theme: jekyll-theme-cayman
title: Gemstone.Configuration
description: GPA Gemstone Configuration Library
github:
  repository_name: gemstone/configuration
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
